#!/bin/bash
echo "
HOST=$(ifconfig wlan0 | grep 'inet' | cut -d: -f2 | awk '{print $2}')
PORT=
USERNAMEDB=admin
PASSWORD=admin123
DATABASE=checkingate
" > /home/pi/demo1.checkingate.mekosoft.vn/web/config/config.env
node web/index 
